# Generated by Django 5.2.8 on 2025-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_placecategory_region_teammember_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#228b57', max_length=20, verbose_name='Цвет линии')),
                ('coordinates', models.JSONField(help_text='Список точек [[lon, lat], [lon, lat], ...]', verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'маршрут',
                'verbose_name_plural': 'маршруты',
            },
        ),
    ]
