# Generated by Django 5.2.8 on 2025-11-20 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.place', verbose_name='Place'),
        ),
    ]
