# Generated by Django 5.1.3 on 2026-01-08 13:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_artifact_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="model_3d",
            field=models.FileField(
                blank=True,
                help_text="3D model (.glb / .gltf)",
                null=True,
                upload_to=core.models.artifact_3d_upload_path,
            ),
        ),
    ]
