# Generated by Django 5.1.3 on 2026-01-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_country_region_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="tour_url",
            field=models.URLField(
                blank=True,
                help_text="Link to virtual tour / route / external map",
                verbose_name="Tour link",
            ),
        ),
    ]
